apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress  # base/ingress.yaml에 있는 이름과 같아야 함
  annotations:
    # 1. GCP 기본 Ingress 컨트롤러(GCE L7 Load Balancer) 사용
    kubernetes.io/ingress.class: gce
